---
- name: configure / SELinux permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux == 'enforcing'

- name: configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
 
- name: configure / Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
 
